[package]
name = "labelr"
version = "0.1.0"
authors = ["Rémy Greinhofer <remy.greinhofer@gmail.com>"]
edition = "2018"
description = "Manage GitHub labels efficiently"
readme = "README.md"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "labelr"
path = "src/lib.rs"

[[bin]]
name = "labelr"
path = "src/main.rs"


[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8.13"
eyre = "0.6.3"
color-eyre = "0.5"
clap = "3.0.0-beta.2"
git2 = "0.13"
git-url-parse = "0.3.0"
tracing = "0.1.22"
tracing-subscriber = "0.2.15"
hubcaps = "0.6"
tokio = { version = "0.2", features = ["macros", "rt-threaded"] }
futures = "0.3"

[dev-dependencies]
tempfile = "3.1.0"
